aliases:
  TomatoBacterialSpot:
    - Tomato_Bacterial_spot
    - tomato_bacterial_spot
    - tomato-bacterial-spot
    - tomato bacterial spot
  TomatoEarlyBlight:
    - Tomato_Early_blight
    - tomato_early_blight
    - tomato-early-blight
    - tomato early blight
  TomatoLateBlight:
    - Tomato_Late_blight
    - tomato_late_blight
    - tomato-late-blight
    - tomato late blight
  TomatoLeafMold:
    - Tomato_Leaf_Mold
    - tomato_leaf_mold
    - tomato-leaf-mold
    - tomato leaf mold
  TomatoSeptoriaLeafSpot:
    - Tomato_Septoria_leaf_spot
    - tomato_septoria_leaf_spot
    - tomato-septoria-leaf-spot
    - tomato septoria leaf spot
  TomatoSpiderMitesTwoSpottedSpiderMite:
    - Tomato_Spider_mites_Two_spotted_spider_mite
    - tomato_spider_mites_two_spotted_spider_mite
    - tomato-spider-mites-two-spotted-spider-mite
    - tomato spider mites two spotted spider mite
  TomatoTargetSpot:
    - Tomato__Target_Spot
    - Tomato_Target_Spot
    - tomato_target_spot
    - tomato-target-spot
    - tomato target spot
  TomatoYellowLeafCurlVirus:
    - Tomato__Tomato_YellowLeaf__Curl_Virus
    - Tomato_YellowLeaf_Curl_Virus
    - tomato_yellowleaf_curl_virus
    - tomato-yellow-leaf-curl-virus
    - tomato yellow leaf curl virus
  TomatoMosaicVirus:
    - Tomato__Tomato_mosaic_virus
    - Tomato_mosaic_virus
    - tomato_mosaic_virus
    - tomato-mosaic-virus
    - tomato mosaic virus
  TomatoHealthy:
    - Tomato_healthy
    - tomato_healthy
    - tomato-healthy
    - tomato healthy
    - Healthy

  TomatoIronDeficiency:
    - Iron_Deficiency
    - iron_deficiency
    - iron-deficiency
    - iron deficiency

  TomatoMagnesiumDeficiency:
    - Magnesium_Deficiency
    - magnesium_deficiency
    - magnesium-deficiency
    - magnesium deficiency

  TomatoManganeseDeficiency:
    - Manganese_Deficiency
    - manganese_deficiency
    - manganese-deficiency
    - manganese deficiency

  TomatoNitrogenDeficiency:
    - Nitrogen_Deficiency
    - nitrogen_deficiency
    - nitrogen-deficiency
    - nitrogen deficiency

  TomatoPhosphorusDeficiency:
    - Phosphorus_Deficiency
    - phosphorus_deficiency
    - phosphorus-deficiency
    - phosphorus deficiency

  TomatoPotassiumDeficiency:
    - Potassium_Deficiency
    - potassium_deficiency
    - potassium-deficiency
    - potassium deficiency

  TomatoHalfRipe:
    - TomatoHalfRipe
    - tomato-half-ripe
    - tomato half ripe
  
  TomatoOverripe:
    - TomatoOverripe
    - tomato-overripe
    - tomato overripe
  
  TomatoRipe:
    - TomatoRipe
    - tomato-ripe
    - tomato ripe
    - ripe
  
  TomatoRotten:
    - TomatoRotten
    - tomato-rotten
    - tomato rotten
    
  TomatoUnripe:
    - TomatoUnripe
    - tomato-unripe
    - tomato unripe
    - unripe
  
  Weeds:
    - weed
  
  PotatoHealthy:
    - Potato_healthy
    - Potato_healthy
    - Potato-healthy
    - Potato healthy
    - Potato___healthy

  PepperBellSpot:
    - Pepper__bell___Bacterial_spot
    - pepper__bell___bacterial_spot
    - pepper-bell-bacterial-spot
    - pepper bell bacterial spot
    - PepperBellBacterialSpot

  PepperBellHealthy:
    - Pepper__bell___healthy
    - pepper__bell___healthy
    - pepper-bell-healthy
    - pepper bell healthy

  PotatoEarlyBlight:
    - Potato___Early_blight
    - potato_early_blight
    - potato-early-blight
    - potato early blight

  PotatoLateBlight:
    - Potato___Late_blight
    - potato_late_blight
    - potato-late-blight
    - potato late blight
  
  Spider:
    - Spider
    - red spider
    - red_spider
