names:
- PepperBellSpot
- PepperBellHealthy
- PotatoEarlyBlight
- PotatoLateBlight
- PotatoHealthy
- TomatoBacterialSpot
- TomatoEarlyBlight
- TomatoLateBlight
- TomatoLeafMold
- TomatoSeptoriaLeafSpot
- TomatoSpiderMitesTwoSpottedSpiderMite
- TomatoTargetSpot
- TomatoYellowLeafCurlVirus
- TomatoMosaicVirus
- TomatoHealthy
- army worm
- black cutworm
- grub
- mole cricket
- peach borer
- Spider
- Ant
- Aphid
- Bee
- Beetle
- Bird
- Caterpillar
- Cockroach
- Earthworms
- Earwig
- Fruit Flies
- Grasshopper
- Moth
- Pests
- Scorpion
- Slug
- Snail
- Wasp
- Weevil
- Weeds
- at risk
- chilli
- fresh
- rotten
- TomatoHalfRipe
- TomatoOverripe
- TomatoRipe
- TomatoRotten
- TomatoUnripe
- TomatoIronDeficiency
- TomatoMagnesiumDeficiency
- TomatoManganeseDeficiency
- TomatoNitrogenDeficiency
- TomatoPhosphorusDeficiency
- TomatoPotassiumDeficiency
- Tomato - S1
- Tomato - S2
- Tomato - S3
- Tomato - S4
- Tomato - S5
- Tomato - S6
- plant
